[package]
name = "diatom-std-core"
version = "0.1.0"
edition.workspace = true
description = "Diatom core standard library"
license.workspace = true
repository.workspace = true

[dependencies]
diatom-core = { path = "../diatom-core", version = "0.6.0" }
ahash.workspace = true
